name: Build module for every architecture

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
        nginx_version: [1.21.6-alpine, 1.22.0-alpine, 1.24.0-alpine, 1.25.3-alpine]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build, tag, and push image
        run: |
          docker buildx build \
            --platform linux/${{ matrix.platform }} \
            --file Dockerfile \
            --build-arg IMAGE=nginx:${{ matrix.nginx_version }} \
            --tag modules:${{ matrix.nginx_version }}-${{ matrix.platform }} \
            --tag modules:latest-${{ matrix.nginx_version }}-${{ matrix.platform }} \
            .

      - name: Save Docker image to file
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker save -o saved-module-image.tar your-username/your-repo:${{ matrix.nginx_version }}-${{ matrix.platform }}-$IMAGE_TAG

      - name: Extract file from saved image
        run: |
          mkdir extracted
          tar xf saved-module-image.tar -C extracted

      - name: Compress extracted file
        run: |
          tar czf otel_ngx_module_${{ matrix.nginx_version }}_${{ matrix.platform }}.tgz -C extracted/usr/lib/nginx/modules otel_ngx_module.so

      - name: Upload extracted file
        uses: actions/upload-artifact@v2
        with:
          name: otel-ngx-module-${{ matrix.nginx_version }}-${{ matrix.platform }}.tgz
          path: otel_ngx_module_${{ matrix.nginx_version }}_${{ matrix.platform }}.tgz

      - name: Upload extracted file as release artifact asset
        if: github.event_name == 'release'
        uses: mkatanski/release-files-action@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
          file-path: otel-ngx-module-${{ matrix.nginx_version }}-${{ matrix.platform }}.tgz
