name: Build module for every architecture

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
        nginx_version: [1.21.6-alpine, 1.22.0-alpine, 1.24.0-alpine, 1.25.3-alpine]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and tag image
        run: |
          docker buildx build \
            --platform linux/${{ matrix.platform }} \
            --file Dockerfile \
            --build-arg IMAGE=nginx:${{ matrix.nginx_version }} \
            --tag module-temp-image \
            --load \
            .

      - name: Run temp container
        run: docker run --name temp-container -d module-temp-image

      - name: Extract module from container
        run: docker cp temp-container:/usr/lib/nginx/modules/otel_ngx_module.so otel_ngx_module.so

      - name: Compress extracted module
        run: |
          tar -cvf otel_ngx_module_${{ matrix.nginx_version }}_${{ matrix.platform }}.tgz otel_ngx_module.so

      - name: Upload extracted file
        uses: actions/upload-artifact@v2
        with:
          name: otel_ngx_module_${{ matrix.nginx_version }}_${{ matrix.platform }}.tgz
          path: otel_ngx_module_${{ matrix.nginx_version }}_${{ matrix.platform }}.tgz

      - name: Upload extracted file as release artifact asset
        if: github.event_name == 'release'
        uses: mkatanski/release-files-action@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
          file-path: otel_ngx_module_${{ matrix.nginx_version }}_${{ matrix.platform }}.tgz
